language: python

python:
- "3.10.9"

services:
- docker
# - mysql

env:
- DJANGO=3.1.3

install:
- pip install -r requirements-prd.txt

script:
- docker-compose run code sh -c "python manage.py test"

    
    

