language: python

dist: focal

python:
  - "3.10"

services:
  - docker
  - mysql

env:
  - DJANGO=3.1.3

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

install:
  - pip install -r requirements-prd.txt

script:
  - python manage.py test
