# Generated by Django 4.1.7 on 2023-03-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
